version: "3.3"

services:
  insightface:
    image: registry.oryza.vn/insightface-rest:v0.9.0.0-gpu
    ports:
      - "18080:18080"
    environment:
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=0
      - PORT=18080
      - NUM_WORKERS=1
      - INFERENCE_BACKEND=onnx
      - DET_NAME=scrfd_2.5g_gnkps
      - DET_THRESH=0.5
      - REC_NAME=w600k_mbf
      - MASK_DETECTOR=None
      - GA_NAME=None
      - KEEP_ALL=True
      - MAX_SIZE=640,640
      - DEF_RETURN_FACE_DATA=False
      - DEF_EXTRACT_EMBEDDING=True
      - DEF_EXTRACT_GA=False
    volumes:
      - "./insightface-rest/models:/models"
      - "./insightface-rest/src:/app"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://insightface:18080/info", "||", "exit", "1"]
      interval: 1m
      timeout: 10s
      retries: 3

