apps:
  - script : ./fastAPI_6000.py
    name   : 'body_server_6000'
#    interpreter: /home/gg_greenlab/anaconda3/envs/openmmlab/bin/python
    interpreter: /home/oryza/miniconda3/envs/head_body_envs/bin/python
#    args: ".env_staging"

