version: "3.3"


services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
